version: '3'

services:
  back:
    build: './back'
    networks:
      - myapp
  front:
    build: './front'
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - myapp

networks:
  myapp:
