version: '3'

services:
  back:
    build: './back'
    networks:
      - myapp
  front:
    build: './front'
    ports:
      - "5000:5000"
    depends_on:
      - back
    networks:
      - myapp

networks:
  myapp:
